### PR TITLE
Adding Coveralls

### PR DESCRIPTION
**Pull request by jabrah**
This PR should add test coverage monitoring to Travis builds. 

Feedback is appreciated, since I've never messed with Travis or Coveralls before! I'm especially not sure if there is a better way to send coverage results to Coveralls in the Travis config. Right now it does some stuff along side the tests:
`npm test && echo "Reporting coveralls" && cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage`

* Let's see if this thing works - testing on my fork seemed to work
* `ember-cli-code-coverage` and `coveralls` is added to the project.
* Coverage can be triggered by setting environment variable `COVERAGE=true`
* You can get the test coverage locally if you want: `COVERAGE=true npm test` which will create a `./coverage` directory with the results.
  * You can't send results to Coveralls locally without the `repo_token`
* So many `package-lock.json` changes

### CODE REVIEW

**Comment by cameronblandford** [comment]
All of this looks great! Just to make sure, have you enabled coveralls for the OA-PASS repo?

**Comment by jabrah** [comment]
Yep, enabled for `OA-PASS/pass-ember`. Do we want it to leave comments on PRs? I just saw a setting for the repo that has comments coveralls comments disabled by default

**Comment by cameronblandford** [comment]
I'm fine just having it in the Checks section. Stays out of the way a little bit more.

**Comment by cameronblandford** [comment]
Also, this looks great, everything is properly configured. Merging!

**Pull request merged**
