### PR TITLE
Set `link` for all submissionEvents

### LINKED ISSUE #776: The `link` field is not set on SubmissionEvents
At present, Ember only populates the `link` field of SubmissionEvents for new users.  However, notification-services expects the `link` to be present in all situations where it might send an e-mail to a user to check on a particular submission.  So at a minimum, it should be set for submissionEvents:
* `approval-requested-newuser`
* `approval-requested`
* `changes-requested`

In fact, it would be ideal to include it on _every_ submissionEvent.

### PR DESCRIPTION
**Pull request by birkland**
Assures that Ember always adds a `link` to SubmissionEvents.

## To test
Notivication services whitelists need tweaking, so the below instructions do not involve looking at any e-mail messages, and can be attempted in `pass-ember`, or `pass-docker`.

***Feel free to test using https://github.com/OA-PASS/pass-docker/pull/163 instead, as it has this PR incorporated into it, and a lot more things work together.  That would be much more pleasant.***

* Start up Ember's docker, or test in pass-docker
* In incognito mode, log in as `staff2`.  Create a proxy submission, search for user `Kirkwood`.
* Close browser, start another incognito session and log in as `nih-user`.  Look at the submissions table, the first one should be the proxy submission.  Look at it, and request changes.
* Close browser, start another incognito session and log in as `staff2`.  Find the proxy submission from the submissions table, and re-submit it for approval
* Close browser..  and log in as `nih-user`.  Either approve or cancel the submission.
* Now go to `http://pass.local:8080/fcrepo/rest/submissionEvents`
  * Foe every submissionEvent, verify that `pass:link` is set.

Resolves #776, #779

### CODE REVIEW

**Comment by karenhanson** [comment]
@birkland Works as described, but do you think the submissions URI needs to be encoded? - wondering if having 2 colons will make it an invalid URI if treated as one. JS has a function for that... https://www.w3schools.com/jsref/jsref_encodeURI.asp

**Comment by birkland** [comment]
@karenhanson It ought to be encoded.  I thought that Hanh created a separate issue for that, but maybe not.  Could amend this PR to do that

**Comment by htpvu** [comment]
@karenhanson @birkland i did create a ticket for that. if you could close 2 ticket with 1 PR, that'd be awesome

**Comment by karenhanson** [comment]
Only the `s.id` needs to be encoded:
`"link" : "https://pass.local%2Fapp%2Fsubmissions%2Fhttps%3A%2F%2Fpass.local%2Ffcrepo%2Frest%2Fsubmissions%2F3d%2Fe3%2Feb%2F40%2F3de3eb40-79df-4429-a94a-355095373b2c"`

**Comment by birkland** [comment]
@karenhanson yes, noticed that.  It takes hours it seems to make a change, see its effect, and notice there was a typo

the `=` sign thing is an issue with notification services

**Comment by htpvu** [comment]
I have not set up a mail client. so i couldn't test this with using `pass-docker`. using `.docker/shib` set up, manually retrieve links and clicking them to verify: this works.

**Pull request merged**
