### PR TITLE
Using Elasticsearch autocomplete service for journal and grants pickers

### PR DESCRIPTION
**Pull request by jabrah**
Needs a good QA pass!

Note this implementation has different behavior compared to the old mocked "autocomplete." This implementation will only offer suggestions where the searched fields are prefixed with the user input. Grants are _not_ yet filtered by logged in user.

Example:
* User types `eng`, attempting to find Advances in Engineering Education. Autocomplete returns no results.
* User types in `adv`, Advances in Engineering Education now appears

**Questions**: 
* Does the Elasticsearch autocomplete service need the user credentials?

### CODE REVIEW

**Comment by jabrah** [comment]
Note there is an open issue in `pass-indexer` which could make it more user-friendly: https://github.com/OA-PASS/pass-indexer/issues/6

**Comment by cameronblandford** [comment]
Sorry for the wait on the review for this - this all looks good, but I'm gonna hold off on merging it until autocomplete behavior improves on ES's side if that's okay with you @jabrah

**Comment by jabrah** [comment]
This PR relates to Issues #279 and #322

**Comment by jabrah** [comment]
Supplanted by the PR 424 (https://github.com/OA-PASS/pass-ember/pull/424), which includes this PR + more changes

**Pull request closed without merging**
